#
# Brain Common Authentication

services:

  brain.common.authentication.storage:
    alias: '%brain.common.api.authentication.storage.service%'

  brain.common.authentication.storage.simple:
    class: 'Brain\Common\Authentication\SimpleAuthenticationStorage'
    public: false
