#
# Brain Common Response

services:

  brain.common.response.factory:
    class: 'Brain\Common\Response\ResponseFactory'
    public: false

  brain.common.response.helper:
    class: 'Brain\Common\Response\ResponseHelper'
    arguments:
      - '@brain.common.response.factory'
      - '@request_stack'
    public: false
