#
# Brain Common Response

services:

  brain.common.response.factory:
    class: 'Brain\Common\Response\ResponseFactory'
    public: false

  brain.common.response.generator:
    class: 'Brain\Common\Response\ResponseGenerator'
    arguments:
      - '@brain.common.response.factory'
      - '@request_stack'
    public: false

  brain.common.response.http.view.factory:
    class: 'Brain\Common\Response\Http\View\HttpViewFactory'
    arguments:
      - '@brain.common.response.generator'
    public: false

  brain.common.response.http.response.factory:
    class: 'Brain\Common\Response\Http\Response\HttpResponseFactory'
    arguments:
      - '@brain.common.response.generator'
    public: false

  brain.common.response.helper:
    class: 'Brain\Common\Response\ResponseHelper'
    arguments:
      - '@brain.common.response.factory'
      - '@request_stack'
    public: false
