#
# Brain Common Translation

services:

  brain.common.translation.translator:
    class: 'Brain\Common\Translation\Translator'
    arguments:
      - '@translator'
      - '%locale%'
    public: false
