#
# Brain Common Utility

services:

  brain.common.utility.factory.identity:
    class: 'Brain\Common\Utility\UniqueIdentityFactory'
    arguments:
      - '@brain.common.utility.factory.identity.uuid'
    public: false

  brain.common.utility.factory.identity.uuid:
    class: 'Ramsey\Uuid\UuidFactory'
    public: false
