#
# Brain Common Components

imports:
  - { resource: component/authentication.yml }
  - { resource: component/database.yml }
  - { resource: component/date.yml }
  - { resource: component/debug.yml }
  - { resource: component/form.yml }
  - { resource: component/response.yml }
  - { resource: component/translation.yml }
  - { resource: component/utility.yml }
