services:

  Brain\Common\Validator\Constraint\Enum\EnumChoiceValidator:
    class: 'Brain\Common\Validator\Constraint\Enum\EnumChoiceValidator'
    tags:
      - { name: validator.constraint_validator }
